version: '3'

services:
    postgres:
      build: ./postgres
      container_name: postgres
      image: "postgres:13.3"
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=sample
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=root
#        TZ: Asia/Seoul
      volumes:
#        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - postgres:/var/lib/postgresql/data
    django:
      build: ./django
      container_name: django
      volumes:
        - ./django:/usr/src/app
    #   environment:
        # - APP_SETTINGS=config.Config
        # - DATABASE_URL=config.Config.SQLALCHEMY_DATABASE_URI
        # - SECRET_KEY=config.Config.SECRET_KEY
      depends_on:
        - postgres
      links:
        - postgres
      ports:
        - "8000:8000"
    spring:
      build: ./spring
      depends_on:
        - postgres
      ports:
        - 8088:8088
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sample
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=root
#      links:
#        - postgres:postgres
    frontend:
      container_name: frontend
      build: ./vue
      ports:
        - 80:80
      expose:
        - "80"
      networks:
        - net
      restart: always
      user: root
#      volumes:
#        - ./nginx/:/usr/share/nginx/
#    nginx:
#      build: vue/nginx
#      container_name: nginx
#      ports:
#        - 80:80
#      restart: always
#      networks:
#        - net
#      volumes:
#        - ./nginx/:/usr/share/nginx/html/static
#    redis:
#      container_name: redis
#      image: redis
#      ports:
#        - "6379:6379"
#      environment:
#        TZ: Asia/Seoul
#    jenkins:
#      build: ./jenkins
#      container_name: jenkins
##      image: jenkins/jenkins:lts-jdk11
#      ports:
#        - 9090:8080
#      user: root
#      volumes:
#        - ./jenkins:/var/jenkinse_home
#      environment:
#        TZ: Asia/Seoul

volumes:
  postgres: {}
  redis: {}
  frontend: {}

networks:
  net: